### ISSUE TITLE
Update dependencies and code

### ISSUE THREAD

**Issue by jens-duttke** [mren/assert-outdated#11]
@mren I know that you're busy and don't have the capacity to work in this project right now.

Since I'm using it in a couple of projects and I think it's a very useful piece of software, I would like to investigate some time in refactoring, if that's OK for you.

- One thing would be to update the dev. dependencies (since they are really outdated).
- Restructure the tests a bit to make creating tests easier
- Restructure the code a bit
- Make use of JSDoc type comments and TypeScript code validation
- Code indention by 4 spaces or 1 tab
- Make use of async/await to increase the readablity

Is that OK for you, or do you want to keep the project as it is?

Especially the last point would require to use Node.js v8 - that's already more than 2 years old, but maybe there are still people using it? Anyway, I think people should be forced to update their systems regularly to get security updates.

**Comment by mren** [comment]
Hey Jens, I am currently on vacation. I will get back to you in around 1 week. Looking forward!

**Comment by jens-duttke** [comment]
@mren I've started working on that, and I've realized that I would need to rewrite almost all the code, so I've decided to start from scratch and write my own package. With slightly different functionality. Sorry.
