### ISSUE TITLE
Ignore specific versions

### ISSUE THREAD

**Issue by jens-duttke** [mren/assert-outdated#6]
I use your module to check that all dependencies are update to date before I release a new version.

One of my projects dependencies is "tslint-microsoft-contrib", their latest version is "6.1.0-beta".
I don't want my project to depend on beta versions (especially because this specific release of tslint-microsoft-contrib is defect).

It would be cool if it would be possible, to specify that versions ending with "-beta" or "-alpha" (or a specific regexp-pattern) should be ignored.  Or if it would be possible to exclude package from the check.

**Comment by mren** [comment]
sure sounds good. What option do you think makes more sense? Would you be interested in doing a pull request? Best!

**Comment by jens-duttke** [comment]
Ok, I'll implement that.

I thought a bit about a good solution, and that's the result:
According https://semver.org the suffix behind the "-" always refers to pre-releases (like "-alpha", "-beta", "-rc").
So I think a good parameter name would be "--ignore-pre-releases".

The question is, what should happen if you already use a pre-release of a package.
e.g. you use package-xy with version "1.0.0-beta.2", and version "1.0.0-beta.4" is the latest package.

In that case it would make sense to me, if this option is only considered if your currently used version is not a pre-release. So in the case above, it would still throw an error.
On the other hand, an update from "6.0.0" to "6.1.0-beta" will be ignored.

What do you think?

The only think that I don't like about that, is: What if there is a release between your installed version and the beta? In the case above e.g. a version "6.0.1". Here it should recommend to update to this version. Unfortunately, I can't find a way to get this information out of npm.

**Comment by mren** [comment]
Thank you Jens, code looks great. I merged your patch and created a new version on npm.
